basePath: /api/v1
host: localhost:8070
info:
  contact:
    email: leminhken124356@gmail.com
    name: Đồ ăn công nghiệp (DACN)
    url: github.com/LeMinh0706/SocialMediaFood-Backend
  description: This is SocialFood Swagger.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/LeMinh0706/SocialMediaFood-Backend
  title: SocialFood Documentations
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
