basePath: /api/v1
definitions:
  response.ErrSwaggerJson:
    properties:
      code:
        type: integer
      error:
        type: string
      return: {}
    type: object
  response.RegisterResponse:
    properties:
      date_create_account:
        type: integer
      email:
        type: string
      fullname:
        type: string
      gender:
        type: integer
      id:
        type: integer
      role_id:
        type: integer
      username:
        type: string
    type: object
  response.RequestResponse:
    properties:
      email:
        type: string
      fullname:
        type: string
      gender:
        maximum: 1
        minimum: 0
        type: integer
      password:
        maxLength: 18
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8070
info:
  contact:
    email: leminhken124356@gmail.com
    name: Đồ ăn công nghiệp (DACN)
    url: github.com/LeMinh0706/SocialMediaFood-Backend
  description: This is SocialFood Swagger.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/LeMinh0706/SocialMediaFood-Backend
  title: SocialFood Documentations
  version: "1.0"
paths:
  /accounts/register:
    post:
      consumes:
      - application/json
      description: register to join socialfood
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/response.RequestResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegisterResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrSwaggerJson'
      summary: Register user
      tags:
      - accounts
swagger: "2.0"
