// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: service_socialfood.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SocialMediaFood_CreateUser_FullMethodName = "/pb.SocialMediaFood/CreateUser"
	SocialMediaFood_LoginUser_FullMethodName  = "/pb.SocialMediaFood/LoginUser"
)

// SocialMediaFoodClient is the client API for SocialMediaFood service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialMediaFoodClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type socialMediaFoodClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialMediaFoodClient(cc grpc.ClientConnInterface) SocialMediaFoodClient {
	return &socialMediaFoodClient{cc}
}

func (c *socialMediaFoodClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, SocialMediaFood_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaFoodClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, SocialMediaFood_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialMediaFoodServer is the server API for SocialMediaFood service.
// All implementations must embed UnimplementedSocialMediaFoodServer
// for forward compatibility.
type SocialMediaFoodServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedSocialMediaFoodServer()
}

// UnimplementedSocialMediaFoodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialMediaFoodServer struct{}

func (UnimplementedSocialMediaFoodServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSocialMediaFoodServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSocialMediaFoodServer) mustEmbedUnimplementedSocialMediaFoodServer() {}
func (UnimplementedSocialMediaFoodServer) testEmbeddedByValue()                         {}

// UnsafeSocialMediaFoodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialMediaFoodServer will
// result in compilation errors.
type UnsafeSocialMediaFoodServer interface {
	mustEmbedUnimplementedSocialMediaFoodServer()
}

func RegisterSocialMediaFoodServer(s grpc.ServiceRegistrar, srv SocialMediaFoodServer) {
	// If the following call pancis, it indicates UnimplementedSocialMediaFoodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialMediaFood_ServiceDesc, srv)
}

func _SocialMediaFood_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaFoodServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaFood_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaFoodServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaFood_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaFoodServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaFood_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaFoodServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialMediaFood_ServiceDesc is the grpc.ServiceDesc for SocialMediaFood service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialMediaFood_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SocialMediaFood",
	HandlerType: (*SocialMediaFoodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SocialMediaFood_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _SocialMediaFood_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_socialfood.proto",
}
