// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   int64       `json:"id"`
	UserID               int64       `json:"user_id"`
	Fullname             string      `json:"fullname"`
	UrlAvatar            string      `json:"url_avatar"`
	UrlBackgroundProfile string      `json:"url_background_profile"`
	Gender               pgtype.Int4 `json:"gender"`
	Country              pgtype.Text `json:"country"`
	Language             pgtype.Text `json:"language"`
	Address              pgtype.Text `json:"address"`
	IsDeleted            bool        `json:"is_deleted"`
	Type                 int32       `json:"type"`
	Location             interface{} `json:"location"`
	IsUpgrade            pgtype.Bool `json:"is_upgrade"`
	Banned               string      `json:"banned"`
}

type AccountPermission struct {
	ID             int64  `json:"id"`
	PermissionName string `json:"permission_name"`
	AccountID      int64  `json:"account_id"`
	CanSelectAll   bool   `json:"can_select_all"`
	CanSelect      bool   `json:"can_select"`
	CanInsert      bool   `json:"can_insert"`
	CanUpdate      bool   `json:"can_update"`
	CanDelete      bool   `json:"can_delete"`
	CanDoAll       bool   `json:"can_do_all"`
}

type AccountType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Follower struct {
	ID            int64  `json:"id"`
	FollowRequest int64  `json:"follow_request"`
	FollowAccept  int64  `json:"follow_accept"`
	Status        string `json:"status"`
}

type Permission struct {
	Name string `json:"name"`
}

type Post struct {
	ID          int64              `json:"id"`
	PostTypeID  int32              `json:"post_type_id"`
	AccountID   int64              `json:"account_id"`
	PostTopID   pgtype.Int8        `json:"post_top_id"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Location    interface{}        `json:"location"`
	IsBanned    bool               `json:"is_banned"`
	IsDeleted   bool               `json:"is_deleted"`
}

type PostImage struct {
	ID       int64  `json:"id"`
	UrlImage string `json:"url_image"`
	PostID   int64  `json:"post_id"`
}

type PostType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type ReactPost struct {
	ID        int64 `json:"id"`
	PostID    int64 `json:"post_id"`
	AccountID int64 `json:"account_id"`
	State     int32 `json:"state"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	HashPassword string             `json:"hash_password"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsDeleted    bool               `json:"is_deleted"`
}
