// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const login = `-- name: Login :one
SELECT id, username, email, created_at FROM users
WHERE username = $1
`

type LoginRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) Login(ctx context.Context, username string) (LoginRow, error) {
	row := q.db.QueryRow(ctx, login, username)
	var i LoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const register = `-- name: Register :one
INSERT INTO users(
    username, 
    email,
    hash_pashword
) VALUES (
    $1, $2, $3
) RETURNING id, username, email, created_at
`

type RegisterParams struct {
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	HashPashword string      `json:"hash_pashword"`
}

type RegisterRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) (RegisterRow, error) {
	row := q.db.QueryRow(ctx, register, arg.Username, arg.Email, arg.HashPashword)
	var i RegisterRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
