info:
  contact: {}
paths:
  /example/hello/{name}:
    get:
      consumes:
      - application/json
      description: just say hello
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
  /pop/ping:
    get:
      consumes:
      - application/json
      description: do pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Bearer: []
      summary: ping pop
      tags:
      - pong
swagger: "2.0"
