basePath: /api/v1
definitions:
  hello.Hello:
    properties:
      id:
        type: integer
      name:
        example: Hiro
        type: string
    required:
    - id
    - name
    type: object
host: localhost:8070
info:
  contact: {}
  description: This is a sample server for Swagger.
  title: SocialFood
  version: "2.0"
paths:
  /example/hello:
    get:
      consumes:
      - application/json
      description: check query
      parameters:
      - description: Name in query
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
    post:
      consumes:
      - application/json
      description: Check Hello struct on repo
      parameters:
      - description: ID and Name here
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/hello.Hello'
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
  /example/hi/{name}:
    get:
      consumes:
      - application/json
      description: check param
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
swagger: "2.0"
