basePath: /api/v1
info:
  contact: {}
paths:
  /example/hello:
    get:
      consumes:
      - application/json
      description: just hello
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - example
  /example/ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
