definitions:
  repo.Hello:
    properties:
      id:
        type: integer
      name:
        example: Hiro
        type: string
    required:
    - id
    - name
    type: object
info:
  contact: {}
paths:
  /example/hello:
    get:
      consumes:
      - application/json
      description: check query
      parameters:
      - description: Name in query
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
    post:
      consumes:
      - application/json
      description: Check Hello struct on repo
      parameters:
      - description: ID and Name here
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/repo.Hello'
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
  /example/hi/{name}:
    get:
      consumes:
      - application/json
      description: check param
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: hello example
      tags:
      - example
  /pop/ping:
    get:
      consumes:
      - application/json
      description: do pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Bearer: []
      summary: ping pop
      tags:
      - pong
swagger: "2.0"
