// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
    post_type_id,
    user_id,
    post_top_id,
    description,
    date_create_post
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, post_type_id, user_id, post_top_id, description, date_create_post
`

type CreatePostParams struct {
	PostTypeID     int64          `json:"post_type_id"`
	UserID         int64          `json:"user_id"`
	PostTopID      sql.NullInt64  `json:"post_top_id"`
	Description    sql.NullString `json:"description"`
	DateCreatePost int64          `json:"date_create_post"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.PostTypeID,
		arg.UserID,
		arg.PostTopID,
		arg.Description,
		arg.DateCreatePost,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PostTypeID,
		&i.UserID,
		&i.PostTopID,
		&i.Description,
		&i.DateCreatePost,
	)
	return i, err
}
