// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Post, error)
	CreateImagePost(ctx context.Context, arg CreateImagePostParams) (PostImage, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePost(ctx context.Context, id int64) error
	GetComment(ctx context.Context, postTopID sql.NullInt64) (Post, error)
	GetImagePost(ctx context.Context, arg GetImagePostParams) (PostImage, error)
	GetListUser(ctx context.Context, arg GetListUserParams) ([]GetListUserRow, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Post, error)
	ListPost(ctx context.Context, arg ListPostParams) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
